### ISSUE TITLE
Error in running installer of FSLeyes Plugin

### ISSUE THREAD

**Issue by KevinBerard** [shimming-toolbox/fsleyes-plugin-shimming-toolbox#11]
### Checklist

- [X] I've given this issue a self-descriptive, meaningful title (e.g. *Installation failure: problem creating launchers*)
- [X] I've described my environment
- [X] I've described the bug
- [X] I've described the steps to reproduce the behaviour
- [X] I've included screenshots
- [X] I've given this issue the correct labels

### Environment details

- [X] I followed the [installation instructions](https://shimming-toolbox.org/en/latest/2_getting_started/1_installation.html)

Project version: 7c52ded8ec39678ea56cf6c556d55a52ff65ff6a

Operating System and version: Ubuntu21

Python version: 3.7 

Path to Python binary: /home/kb/anaconda3/envs/shim_venv/bin/python 

### Bug Description

The installation is not proceding.

### Reproduction Steps

Freshly installed Ubuntu21 with installation of dcm2niix and FSL according to the [guide](https://shimming-toolbox.org/en/latest/getting_started/installation_st/linux.html) . After, I followed the [steps](https://shimming-toolbox.org/en/latest/getting_started/installation_gui.html) to install the FSLeyes Plugin to get stuck at the step where you need to run the installer with "make install".

### Screenshots:

![Screenshot from 2021-05-26 15-12-11](https://user-images.githubusercontent.com/83981856/119720137-9a87c580-be37-11eb-9534-8720378879ad.png)

**Comment by po09i** [comment]
This seems like a permission problem where sudo could fix this. However this is probably not best practice to require users to use sudo when they install the plugin. More info [here](https://unix.stackexchange.com/questions/20953/difference-between-make-install-and-sudo-make-install). We should try to find why it's asking for more permissions and potentially fix it if we can.

**Comment by ahill187** [comment]
Discussed with Nick Guenther last week, I don't think this is an error related to the `fsleyes-plugin-shimming-toolbox` package. Likely, an install of another package or an update created a lock which is now blocking the install.

**Comment by kousu** [comment]
This is why in SCT instead of running `apt-get install` for you, we [just](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/8969ecd82801ff037ce7752098bf2fce9cee5032/install_sct#L179-L181)

```
  if [[ ! ( $(command -v curl) || $(command -v wget) ) ]]; then
    die "ERROR: neither \"curl\" nor \"wget\" is installed. Please install either of them and restart SCT installation."
  fi
```

and are planning (https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/1526) to make `pip install spinalcordtoolbox` work, which, by using `entry_points`, will take care of deploying executables to the right places.

I kind of think unless you provide a complete VM image for someone to run (which is extremely expensive in bandwidth; it maybe makes sense for datacenters, but not for end users) then you need to leave some parts manual, and "make sure you have curl" is a reasonable one.
